'use client'

import { useState, useEffect } from 'react'
import { AlertTriangle, Radio, CheckCircle2, Download } from 'lucide-react'
import { MonoBadge, StatusChip } from '@/components/ui/primitives'

export function StrategyPage() {
  const [result, setResult] = useState('')
const [idea, setIdea] = useState('')

useEffect(() => {
  const stored = localStorage.getItem('vectra-result')
  const storedIdea = localStorage.getItem('vectra-idea')
  if (stored) setResult(stored)
  if (storedIdea) setIdea(storedIdea)
}, [])
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', minHeight: 'calc(100vh - 84px)' }}>

      {/* ── Main ── */}
      <div style={{ padding: 28, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 20 }}>

        {/* Dossier header */}
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
            <MonoBadge color="#EF4444">CLASSIFIED</MonoBadge>
            <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: '#4A5568' }}>DOSSIER ID: VCTR-294-X</span>
          </div>
          <h1 style={{ fontFamily: "'Sora', sans-serif", fontSize: 34, fontWeight: 800, color: '#E6EEF8', lineHeight: 1.1 }}>Project Obsidian</h1>
          <h1 style={{ fontFamily: "'Sora', sans-serif", fontSize: 34, fontWeight: 800, color: '#4F7CFF', lineHeight: 1.1, marginBottom: 12 }}>
            Market Dominance Protocol
          </h1>
          <div style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
            {[
              { label: 'GENERATED BY', val: 'VECTRA STRATEGIC AI CORE' },
              { label: 'CYCLE TIME',   val: '482MS' },
            ].map(({ label, val }) => (
              <div key={label}>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#4A5568', letterSpacing: '0.1em', marginBottom: 2 }}>{label}</div>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: '#94A3B8', letterSpacing: '0.08em' }}>{val}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Strategic reading */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 24 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#22D3EE', letterSpacing: '0.15em', marginBottom: 14 }}>STRATEGIC READING</div>
          <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 13, color: '#94A3B8', lineHeight: 1.8, marginBottom: 16 }}>
            The current market topography indicates a significant structural deficit in high-latency defense mechanisms. Competitor activity is localized to standardized SaaS architectures, creating a{' '}
            <span style={{ color: '#4F7CFF', textDecoration: 'underline' }}>strategic vacuum</span>{' '}
            within sovereign data processing layers.
          </p>
          <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 13, color: '#94A3B8', lineHeight: 1.8 }}>
            Deployment of the Obsidian Protocol will prioritize the encapsulation of legacy assets while simultaneously deploying parallel-processed edge nodes. This allows for total market saturation with zero detectable overhead.
          </p>
          {/* Bar chart viz */}
          <div style={{ marginTop: 18, height: 80, background: '#05070F', borderRadius: 6, display: 'flex', alignItems: 'flex-end', gap: 3, padding: '0 12px 12px', overflow: 'hidden', position: 'relative' }}>
            <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse at 30% 50%, rgba(79,124,255,0.1), transparent 60%)' }} />
            {[35, 55, 28, 70, 42, 88, 50, 62, 38, 75, 45, 90, 55, 68, 40, 82, 48, 72, 35, 65].map((h, i) => (
              <div
                key={i}
                style={{
                  flex: 1, borderRadius: '2px 2px 0 0',
                  background: `rgba(79,124,255,${0.2 + (h / 100) * 0.6})`,
                  height: `${h}%`,
                }}
              />
            ))}
          </div>
        </div>

        {/* Recommended build direction */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 24 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', letterSpacing: '0.15em', marginBottom: 14 }}>RECOMMENDED BUILD DIRECTION</div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div style={{ flex: 1 }}>
              <h2 style={{ fontFamily: "'Sora', sans-serif", fontSize: 22, fontWeight: 800, color: '#E6EEF8', marginBottom: 12 }}>Sovereign Edge Deployment</h2>
              <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, color: '#64748B', lineHeight: 1.7, maxWidth: 420 }}>
                Autonomous infrastructure that self-heals and optimizes without human intervention. Built for high-stakes environments where latency is the only metric of failure.
              </p>
            </div>
            <div style={{ textAlign: 'right', flexShrink: 0, marginLeft: 24 }}>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', marginBottom: 4 }}>CONFIDENCE</div>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 26, fontWeight: 700, color: '#22D3EE' }}>98.4%</div>
            </div>
          </div>
        </div>

        {/* Differentiation + Critical weaknesses */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 22 }}>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#22D3EE', letterSpacing: '0.15em', marginBottom: 14 }}>DIFFERENTIATION STRATEGY</div>
            <h3 style={{ fontFamily: "'Sora', sans-serif", fontSize: 15, fontWeight: 700, color: '#E6EEF8', marginBottom: 10 }}>The Moat Principle</h3>
            <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, color: '#64748B', lineHeight: 1.7, marginBottom: 18 }}>
              Unlike competitors focusing on UI/UX, obsidian protocol builds deep integration layers into existing hardware stacks, making switching costs insurmountable.
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              {[
                { label: 'LEVERAGE', val: '8.4x Structural' },
                { label: 'ENTROPY',  val: '0.02% Residual' },
              ].map(({ label, val }) => (
                <div key={label} style={{ background: '#05070F', border: '1px solid #1E293B', borderRadius: 6, padding: '10px 12px' }}>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#4A5568', marginBottom: 4 }}>{label}</div>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#E6EEF8' }}>{val}</div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 22 }}>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#EF4444', letterSpacing: '0.15em', marginBottom: 14 }}>CRITICAL WEAKNESSES</div>
            {[
              { Icon: AlertTriangle, color: '#EF4444', title: 'Legacy Friction',      desc: 'Old systems may reject the obsidian encapsulation protocols during Phase 1.' },
              { Icon: Radio,         color: '#F59E0B', title: 'Bandwidth Throttling', desc: 'Potential ISP-level detection of non-standard data packets.' },
            ].map(({ Icon, color, title, desc }, i) => (
              <div key={i} style={{ marginBottom: 14 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                  <Icon size={13} color={color} />
                  <span style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, fontWeight: 600, color: '#E6EEF8' }}>{title}</span>
                </div>
                <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 11, color: '#64748B', lineHeight: 1.5 }}>{desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Rejected alternatives */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 22 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', letterSpacing: '0.15em', marginBottom: 16 }}>REJECTED ALTERNATIVES (STRATEGIC DISMISSAL)</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
            {[
              { title: 'CLOUD-NATIVE HYBRID',  reason: 'Vulnerable to third-party vendor lock-in and high-latency bias. Dismissed for lack of sovereignty.' },
              { title: 'DECENTRALIZED MESH',   reason: 'Inefficient throughput for real-time strategic maneuvers. Complexity increases execution risk.' },
              { title: 'LEGACY API WRAP',      reason: 'Fails Core Performance requirements. Risk of key systems failure under load.' },
            ].map(({ title, reason }, i) => (
              <div key={i} style={{ opacity: 0.55 }}>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', letterSpacing: '0.1em', marginBottom: 8, textDecoration: 'line-through' }}>{title}</div>
                <p style={{ fontFamily: "'Sora', sans-serif", fontSize: 11, color: '#4A5568', lineHeight: 1.6 }}>{reason}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Execution timeline + MVP scope */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 22 }}>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#22D3EE', letterSpacing: '0.15em', marginBottom: 18 }}>EXECUTION TIMELINE</div>
            {[
              { phase: 'Phase Alpha: Initial Infiltration', period: 'Weeks 1–4: Edge node deployment and baseline establish.', active: true },
              { phase: 'Phase Beta: Protocol Escalation',   period: 'Weeks 5–12: Full market saturation and competitor suppression.', active: false },
              { phase: 'Phase Omega: Total Hegemony',       period: 'Weeks 13+: Final systemic lock and perpetual optimization loop.', active: false },
            ].map(({ phase, period, active }, i) => (
              <div key={i} style={{ display: 'flex', gap: 14, marginBottom: 18 }}>
                <div
                  style={{
                    width: 12, height: 12, borderRadius: '50%', flexShrink: 0, marginTop: 3,
                    background: active ? '#22D3EE' : '#1E293B',
                    border: `2px solid ${active ? '#22D3EE' : '#4A5568'}`,
                    boxShadow: active ? '0 0 8px #22D3EE' : 'none',
                  }}
                />
                <div>
                  <div style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, fontWeight: 600, color: active ? '#E6EEF8' : '#64748B', marginBottom: 4 }}>{phase}</div>
                  <div style={{ fontFamily: "'Sora', sans-serif", fontSize: 11, color: '#4A5568' }}>{period}</div>
                </div>
              </div>
            ))}
          </div>

          <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 22 }}>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#22D3EE', letterSpacing: '0.15em', marginBottom: 16 }}>MVP SCOPE: MINIMUM VIABLE DOMINANCE</div>
            {[
              { title: 'Zero-Trust Backbone:', desc: 'Immediate security hardening of current assets.' },
              { title: 'AI Triage:',           desc: 'Autonomous sorting of inbound threat vectors.' },
              { title: 'Core Ledger:',         desc: 'Immutable audit trail of all strategic decisions.' },
            ].map(({ title, desc }, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, marginBottom: 14 }}>
                <CheckCircle2 size={14} color="#10B981" style={{ flexShrink: 0, marginTop: 2 }} />
                <div style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, color: '#94A3B8' }}>
                  <strong style={{ color: '#E6EEF8' }}>{title}</strong> {desc}
                </div>
              </div>
            ))}
            <div style={{ marginTop: 16, background: '#05070F', border: '1px solid #1E293B', borderRadius: 6, padding: 12 }}>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#EF4444', letterSpacing: '0.1em', marginBottom: 8 }}>CRITICAL FAILURE POINTS</div>
              {[
                '> 01. INCOMPLETE HARDWARE HANDSHAKES DURING PHASE 1',
                '> 02. EXTERNAL REGULATORY INJECTION',
                '> 03. RESOURCE EXHAUSTION IN DEEP-EDGE NODES',
              ].map((line, i) => (
                <div key={i} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#4A5568', lineHeight: 1.8 }}>{line}</div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* ── Right Rail ── */}
      <div style={{ padding: '28px 20px', borderLeft: '1px solid #1E293B', display: 'flex', flexDirection: 'column', gap: 16, overflowY: 'auto' }}>

        {/* Feasibility verdict */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 20 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#22D3EE', letterSpacing: '0.12em', marginBottom: 16 }}>FEASIBILITY VERDICT</div>
          <div style={{ textAlign: 'center', marginBottom: 16 }}>
            <div
              style={{
                width: 80, height: 80, borderRadius: '50%',
                border: '3px solid #22D3EE',
                boxShadow: '0 0 20px rgba(34,211,238,0.3)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto',
              }}
            >
              <div>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 18, fontWeight: 800, color: '#22D3EE', textAlign: 'center' }}>GO</div>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 8, color: '#64748B', textAlign: 'center' }}>MISSION STATUS</div>
              </div>
            </div>
          </div>
          {[
            { label: 'RESOURCE LOAD',   val: 'OPTIMAL',       color: '#10B981' },
            { label: 'MARKET ENTRY',    val: 'HIGH VELOCITY', color: '#22D3EE' },
            { label: 'RISK COEFFICIENT', val: '0.12 NEGATIVE', color: '#EF4444' },
          ].map(({ label, val, color }) => (
            <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid #1E293B' }}>
              <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B' }}>{label}</span>
              <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color }}>{val}</span>
            </div>
          ))}
          <button
            style={{
              width: '100%', marginTop: 14, padding: 10,
              background: 'transparent', border: '1px solid #1E293B',
              borderRadius: 5, color: '#94A3B8',
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
              cursor: 'pointer', letterSpacing: '0.1em',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            }}
          >
            <Download size={11} /> DOWNLOAD RAW INTELLIGENCE
          </button>
        </div>

        {/* Core strengths */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 18 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', letterSpacing: '0.12em', marginBottom: 12 }}>CORE STRENGTHS</div>
          {['Neural Asymmetry', 'Total Resource Isolation'].map((s, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
              <div style={{ width: 5, height: 5, background: '#4F7CFF', borderRadius: 1 }} />
              <span style={{ fontFamily: "'Sora', sans-serif", fontSize: 12, color: '#94A3B8' }}>{s}</span>
            </div>
          ))}
        </div>

        {/* Status chips */}
        <div style={{ background: '#0A0F1C', border: '1px solid #1E293B', borderRadius: 10, padding: 18 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: '#64748B', letterSpacing: '0.12em', marginBottom: 12 }}>EXECUTION FLAGS</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <StatusChip label="ANALYSIS COMPLETE" color="#10B981" />
            <StatusChip label="SCOPE RISK DETECTED" color="#F59E0B" />
            <StatusChip label="WEAK PATH REJECTED" color="#EF4444" />
            <StatusChip label="EXECUTION PATH SELECTED" color="#4F7CFF" />
          </div>
        </div>
      </div>
    </div>
  )
}
